language: c
compiler: clang
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libffi-dev libbsd-dev libpcre3-dev libgc-dev realpath libcurl4-openssl-dev libsparsehash-dev sparsehash
install:
  - cd autohell && aclocal && libtoolize && autoconf && automake --add-missing
  - mkdir -p build && mkdir -p basemods && export BUILD_DIR_INT=$(realpath build)
  - cd src/tcc && ./configure && make && sudo make install && cd ../..
  - ./configure --prefix=$BUILD_DIR_INT && make
  - cd .. && bash ./makeplugs.sh
  - cd autohell
  - make install
  - cd ..

script:
  - echo "bash ./runtests.sh autohell/build/bin"
  - export VERSION=$(git rev-parse --short HEAD)

after_success:
  - wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - mkdir -p appimage/AppDir/usr && cp -r autohell/build/* appimage/AppDir/usr
  - mkdir -p appimage/AppDir/usr/share/application
  - mkdir -p appimage/AppDir/usr/share/icons/hicolor/256x256
  - cp image/citron.png appimage/AppDir/usr/share/icons/hicolor/256x256/
  - echo "[Desktop Entry]" > appimage/AppDir/usr/share/application/citron.desktop
  - echo "Type=Application" >> appimage/AppDir/usr/share/application/citron.desktop
  - echo "Name=Citron" >> appimage/AppDir/usr/share/application/citron.desktop
  - echo "Comment=Citron Interp" >> appimage/AppDir/usr/share/application/citron.desktop
  - echo "Exec=ctr" >> appimage/AppDir/usr/share/application/citron.desktop
  - echo "Icon=citron" >> appimage/AppDir/usr/share/application/citron.desktop
  - echo "Categories=Development;" >> appimage/AppDir/usr/share/application/citron.desktop
  - echo "Terminal=true" >> appimage/AppDir/usr/share/application/citron.desktop # Needed for CLI tools
  - ./linuxdeployqt-continuous-x86_64.AppImage appimage/AppDir/usr/share/application/citron.desktop -appimage
  - cp --force Citron*.AppImage autohell/build/bin/ctr
  - ls -lh autohell/build/*
  - ls -lh *.AppImage
  - tar cjf release.tar.bz2 -C autohell/build .
  - (cd autohell/build && zip -r - .) > release.zip
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh release.tar.bz2 release.zip Citron*.AppImage*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
