language: c
compiler: clang
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libffi-dev libbsd-dev libpcre3-dev libgc-dev realpath
install:
  - cd autohell && aclocal && libtoolize && autoconf && automake --add-missing
  - mkdir -p build && ./configure --prefix=$(realpath ./build) && make
  - cd .. && bash ./makeplugs.sh

script:
  - bash ./runtests.sh autohell/build
