language: c
compiler: clang
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libffi-dev libbsd-dev libpcre3-dev libgc-dev realpath libcurl4-openssl-dev
install:
  - cd autohell && aclocal && libtoolize && autoconf && automake --add-missing
  - mkdir -p build && ./configure --prefix=$(realpath ./build) && make
  - cd .. && bash ./makeplugs.sh
  - cd autohell
  - make install
  - cd ..

script:
  - echo "bash ./runtests.sh autohell/build/bin" #Ignore tests for now

after_success:
  - ls -lh autohell/build/*
  - tar cjf release.tar.bz2 -C autohell/build .
  - (cd autohell/build && zip -r - .) > release.zip
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh release.tar.bz2 release.zip

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
