#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.0.8.6-{branch}-{build}

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

# branches to build
branches:
  # whitelist
  only:
    - windows
  except:
    - /^(?i:continuous)$/

matrix:
      allow_failures:
        - prepare_mode: YES

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Including commits with particular message or from specific user
only_commits:
  message: /build/                # Start a new build if message contains 'build'

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

environment:
  auth_token:
    secure: yFpDwb0WUOt3DSroBeI3vHzs+leUiIZPxCn80XUSVzdK22RgzqwQFQbADIvyTSNJ
  matrix:
    - prepare_mode: YES
    - prepare_mode: NO
      COMPILER: msys2
      PLATFORM: x86
      MSYS2_ARCH: x86
      MSYS2_DIR: msys64
      MSYSTEM: MINGW32

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf false

# clone directory
clone_folder: c:\projects\citron

# set clone depth
clone_depth: 5                      # clone entire repository history if not defined

# scripts that run after cloning repository
install:
  - md c:\ciuploadtool
  - cd c:\ciuploadtool
  - curl -fsSL https://github.com/d1vanov/ciuploadtool/releases/download/continuous-master/ciuploadtool_windows_x86.zip -o ciuploadtool_windows_x86.zip
  - 7z x ciuploadtool_windows_x86.zip

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release

# to run your custom scripts instead of automatic MSBuild
build_script:
  - if %prepare_mode%==YES c:\ciuploadtool\ciuploadtool.exe -preponly -suffix="%APPVEYOR_REPO_BRANCH%"
  - if %prepare_mode%==YES exit 1
  - '%APPVEYOR_BUILD_FOLDER%\build_windows_package.bat'

on_finish:
  - c:\ciuploadtool\ciuploadtool.exe -suffix="%APPVEYOR_REPO_BRANCH%" citron-release.tar

# to disable automatic builds
build: off

#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:

  # Email
  - provider: Email
    to:
      - ali.mpfard@gmail.com
    subject: 'Build {{status}}'                  # optional
    message: "{{message}}, {{commitId}}, ..."    # optional
    on_build_status_changed: true
